language: node_js

node_js:
  - 12.18.1

branches:
  only:
    - master

jobs:
  include:
    - name: "Jest + Enzyme Tests"
      script:
        - yarn install
        - yarn test

before_install:
  - openssl aes-256-cbc -K $encrypted_01ee5a5a4535_key -iv $encrypted_01ee5a5a4535_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
